<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="InterfaceManager_test" Id="{30c1cd6d-f339-00e4-1a35-d57ebc4aab31}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK InterfaceManager_test EXTENDS TcUnit.FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[test_InitTwice();
]]></ST>
    </Implementation>
    <Method Name="test_InitTwice" Id="{fb69b5fe-8ee4-0c60-166e-2e9d1eff7b35}">
      <Declaration><![CDATA[METHOD test_InitTwice
VAR_INPUT
END_VAR
VAR 
	fb_1 : InterfaceManager;
//	fb_2 : InterfaceManager;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('test_InitTwice');



TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>