<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{040816f1-f230-4b7f-abf9-ea3a3ab6afb7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	linear_phy_to_adc_test_ 		: linear_phy_to_adc_test;
	linear_adc_to_phy_test_ 		: linear_adc_to_phy_test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>